#!/usr/bin/env bash
# Script that configures hosts file

sudo grep -v "localhost" /etc/hosts | sudo tee /etc/hosts.tmp > /dev/null
sudo mv /etc/hosts.tmp /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

sudo grep -v "facebook.com" /etc/hosts | sudo tee /etc/hosts.tmp > /dev/null
sudo mv /etc/hosts.tmp /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
